const axios = require("axios");
const fs = require("fs");
const path = require("path");

module.exports = {
  config: {
    name: "pixart",
    version: "4.3",
    author: "Hazeyy | Fixed by GPT-5",
    countDown: 5,
    role: 0,
    shortDescription: "Generate AI art from text",
    longDescription: "Generate AI-based art using PixArt XL API.",
    category: "ai",
    guide: {
      en: "{pn} <prompt>\nExample: {pn} cyberpunk city at night",
    },
  },

  // ✅ When user runs: !pixart <prompt>
  onStart: async function ({ api, event, args }) {
    const { threadID } = event;

    if (args.length === 0) {
      return api.sendMessage(
        "✨ Please provide a prompt.\nExample:\n`pixart cat wearing sunglasses`",
        threadID
      );
    }

    const prompt = args.join(" ");
    api.sendMessage("🕟 | Generating your PixArt image, please wait...", threadID);

    try {
      const res = await axios.get("https://codemerge-api.hazeyy0.repl.co/pixart/api", {
        params: { prompt },
      });

      const data = res.data;
      if (!data) throw new Error("No response from API");

      // Handle array or single URL
      const imageUrl = Array.isArray(data) ? data[0] : data.url || data.image || data;

      if (!imageUrl || typeof imageUrl !== "string") {
        throw new Error("Invalid image URL from API");
      }

      const imageRes = await axios.get(imageUrl, { responseType: "arraybuffer" });

      const cacheDir = path.join(__dirname, "cache");
      if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir);

      const imgPath = path.join(cacheDir, `${Date.now()}.jpg`);
      fs.writeFileSync(imgPath, imageRes.data);

      const message = `🤖 𝐏𝐢𝐱𝐀𝐫𝐭 (𝐀𝐈)\n\n🖋️ Prompt: "${prompt}"\n✨ Generated by PixArt XL`;

      api.sendMessage(
        {
          body: message,
          attachment: fs.createReadStream(imgPath),
        },
        threadID,
        () => fs.unlinkSync(imgPath)
      );
    } catch (error) {
      console.error("🚫 PixArt Error:", error.message || error);
      api.sendMessage("🚫 An error occurred while generating the image.", threadID);
    }
  },
};
